// Local Expo config plugin: let the app connect to a WildClaude server that
// serves HTTPS with a self-signed certificate.
//
// React Native's fetch validates server certs against the system trust store,
// so a self-signed cert is rejected. We install a custom OkHttpClientFactory
// (Android) that accepts the server's TLS cert. This is trust-on-pairing: the
// app only ever talks to a server the user explicitly paired with, and it is
// strictly more private than the plain-HTTP path we also allow — appropriate
// for a personal tool reached over LAN / Tailscale. (A future hardening can
// verify the cert SHA-256 we already capture during pairing; see pair.ts.)
//
// NOTE: Android only. iOS would need an equivalent NSURLSession delegate.

const { withMainApplication, withDangerousMod } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

const ANDROID_PACKAGE = 'ai.wildclaude.app';

const FACTORY_KT = `package ${ANDROID_PACKAGE}

import com.facebook.react.modules.network.OkHttpClientFactory
import com.facebook.react.modules.network.OkHttpClientProvider
import okhttp3.OkHttpClient
import java.security.SecureRandom
import java.security.cert.X509Certificate
import javax.net.ssl.SSLContext
import javax.net.ssl.TrustManager
import javax.net.ssl.X509TrustManager

/**
 * OkHttp client that trusts the server's TLS certificate, so a WildClaude
 * server with a self-signed cert is reachable. Generated by the
 * withSelfSignedTrust config plugin — edits here are overwritten on prebuild.
 */
class SelfSignedOkHttpClientFactory : OkHttpClientFactory {
  override fun createNewNetworkModuleClient(): OkHttpClient {
    val trustManager = object : X509TrustManager {
      override fun checkClientTrusted(chain: Array<out X509Certificate>?, authType: String?) {}
      override fun checkServerTrusted(chain: Array<out X509Certificate>?, authType: String?) {}
      override fun getAcceptedIssuers(): Array<X509Certificate> = arrayOf()
    }
    val sslContext = SSLContext.getInstance("TLS")
    sslContext.init(null, arrayOf<TrustManager>(trustManager), SecureRandom())
    return OkHttpClientProvider.createClientBuilder()
      .sslSocketFactory(sslContext.socketFactory, trustManager)
      .hostnameVerifier { _, _ -> true }
      .build()
  }
}
`;

const REGISTER_LINE =
  '    com.facebook.react.modules.network.OkHttpClientProvider.setOkHttpClientFactory(SelfSignedOkHttpClientFactory())';

const withSelfSignedTrust = (config) => {
  // 1. Write the factory next to MainApplication.
  config = withDangerousMod(config, [
    'android',
    async (cfg) => {
      const dir = path.join(
        cfg.modRequest.platformProjectRoot,
        'app/src/main/java',
        ...ANDROID_PACKAGE.split('.'),
      );
      fs.mkdirSync(dir, { recursive: true });
      fs.writeFileSync(path.join(dir, 'SelfSignedOkHttpClientFactory.kt'), FACTORY_KT);
      return cfg;
    },
  ]);

  // 2. Register the factory early in MainApplication.onCreate().
  config = withMainApplication(config, (cfg) => {
    let src = cfg.modResults.contents;
    if (!src.includes('setOkHttpClientFactory')) {
      src = src.replace('super.onCreate()', `super.onCreate()\n${REGISTER_LINE}`);
    }
    cfg.modResults.contents = src;
    return cfg;
  });

  return config;
};

module.exports = withSelfSignedTrust;
