/**
 * Declarative dashboard engine.
 *
 * A dashboard is a JSON SPEC of widgets; the frontend renders any spec
 * generically and this module resolves each widget's data server-side (so
 * secrets and CORS are handled here, never in the browser). Specs can be:
 *   - hand-built / template-instantiated
 *   - generated by the LLM from a plain-language request ("make me a crypto dashboard")
 *   - scoped to a project container
 *
 * Widget data sources:
 *   - http   : fetch a JSON API, extract via a dotted path; {{SECRET}} placeholders
 *              in url/headers are filled from the encrypted secret store
 *   - rss     : fetch + parse an RSS/Atom feed
 *   - local   : query the dashboard_data table (tracker widgets; forms write here)
 *   - static  : a literal value
 *
 * Specs live in USER_DATA_DIR/dashboards/<id>.json (versioned in the user-data repo).
 */

import fs from 'fs';
import path from 'path';
import type { Hono } from 'hono';

import { USER_DATA_DIR } from './paths.js';
import { logger } from './logger.js';
import { insertDashboardData, queryDashboardData } from './db.js';
import { DEFAULT_DASHBOARD_TEMPLATES } from './dashboard-templates.js';

// ── Types ──────────────────────────────────────────────────────────────

export type WidgetType = 'metric' | 'chart' | 'table' | 'list' | 'feed' | 'form' | 'note';

export interface WidgetSource {
  kind: 'http' | 'rss' | 'local' | 'static';
  // http
  url?: string;
  headers?: Record<string, string>;
  method?: string;
  jsonPath?: string;          // dotted path into the JSON response (e.g. "data.0.current_price")
  // rss
  limit?: number;
  // local
  field?: string;             // which field of each entry to aggregate/plot
  agg?: 'sum' | 'avg' | 'count' | 'last' | 'list';
  sinceDays?: number;
  groupByDay?: boolean;
  // static
  value?: unknown;
}

export interface Widget {
  id: string;
  type: WidgetType;
  title: string;
  w?: number;                 // grid columns 1–12 (default 4)
  source?: WidgetSource;
  config?: Record<string, unknown>; // type-specific (unit, columns, fields[], etc.)
  refreshSec?: number;
}

export interface DashboardSpec {
  id: string;
  title: string;
  icon?: string;
  description?: string;
  widgets: Widget[];
  projectId?: string;
  builtinTemplate?: string;
  createdAt: number;
  updatedAt: number;
}

const DASH_DIR = path.join(USER_DATA_DIR, 'dashboards');

// ── Store ──────────────────────────────────────────────────────────────

function specPath(id: string): string {
  // Guard against traversal — ids are slugs.
  const clean = String(id).replace(/[^a-z0-9_-]/gi, '');
  return path.join(DASH_DIR, `${clean}.json`);
}

export function listDashboards(projectId?: string): DashboardSpec[] {
  try {
    if (!fs.existsSync(DASH_DIR)) return [];
    const specs: DashboardSpec[] = [];
    for (const f of fs.readdirSync(DASH_DIR)) {
      if (!f.endsWith('.json')) continue;
      try {
        const s = JSON.parse(fs.readFileSync(path.join(DASH_DIR, f), 'utf8')) as DashboardSpec;
        if (projectId === undefined || s.projectId === projectId) specs.push(s);
      } catch { /* skip corrupt */ }
    }
    return specs.sort((a, b) => (b.updatedAt || 0) - (a.updatedAt || 0));
  } catch { return []; }
}

export function getDashboard(id: string): DashboardSpec | null {
  try { return JSON.parse(fs.readFileSync(specPath(id), 'utf8')) as DashboardSpec; } catch { return null; }
}

const slugify = (s: string) => (s || 'dashboard').toLowerCase().trim().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '').slice(0, 40) || 'dashboard';

/** Validate + normalize a raw spec object (from LLM/import/template). */
export function normalizeSpec(raw: Partial<DashboardSpec>, opts: { id?: string; projectId?: string } = {}): DashboardSpec {
  const now = Date.now();
  const id = opts.id || slugify(raw.id || raw.title || 'dashboard') + '-' + now.toString(36).slice(-4);
  const widgets: Widget[] = (Array.isArray(raw.widgets) ? raw.widgets : []).slice(0, 30).map((w, i) => ({
    id: (w as Widget).id || `w${i}`,
    type: (['metric', 'chart', 'table', 'list', 'feed', 'form', 'note'].includes((w as Widget).type) ? (w as Widget).type : 'note') as WidgetType,
    title: String((w as Widget).title || 'Widget').slice(0, 120),
    w: Math.min(12, Math.max(1, (w as Widget).w || 4)),
    source: (w as Widget).source,
    config: (w as Widget).config || {},
    refreshSec: (w as Widget).refreshSec,
  }));
  return {
    id,
    title: String(raw.title || 'Dashboard').slice(0, 120),
    icon: String(raw.icon || '📊').slice(0, 8),
    description: raw.description ? String(raw.description).slice(0, 400) : undefined,
    widgets,
    projectId: opts.projectId ?? raw.projectId,
    builtinTemplate: raw.builtinTemplate,
    createdAt: raw.createdAt || now,
    updatedAt: now,
  };
}

export function saveDashboard(spec: DashboardSpec): DashboardSpec {
  fs.mkdirSync(DASH_DIR, { recursive: true });
  const normalized = { ...spec, updatedAt: Date.now() };
  fs.writeFileSync(specPath(spec.id), JSON.stringify(normalized, null, 2));
  return normalized;
}

export function deleteDashboard(id: string): boolean {
  try { fs.unlinkSync(specPath(id)); return true; } catch { return false; }
}

// ── Templates ──────────────────────────────────────────────────────────

export function listTemplates(): Array<{ id: string; title: string; icon: string; description: string }> {
  return DEFAULT_DASHBOARD_TEMPLATES.map((t) => ({ id: t.id, title: t.title, icon: t.icon || '📊', description: t.description || '' }));
}

export function instantiateTemplate(templateId: string, opts: { projectId?: string } = {}): DashboardSpec | null {
  const tpl = DEFAULT_DASHBOARD_TEMPLATES.find((t) => t.id === templateId);
  if (!tpl) return null;
  const spec = normalizeSpec({ ...tpl, builtinTemplate: templateId }, { projectId: opts.projectId });
  return saveDashboard(spec);
}

// ── SSRF guard + secret substitution ─────────────────────────────────────

function safeHttpUrl(url: string): boolean {
  let u: URL;
  try { u = new URL(url); } catch { return false; }
  if (u.protocol !== 'https:') return false;
  const h = u.hostname.toLowerCase();
  if (h === 'localhost' || h === '::1' || h.endsWith('.local') || h.endsWith('.internal') || !h.includes('.')) return false;
  if (/^127\.|^10\.|^192\.168\.|^169\.254\.|^172\.(1[6-9]|2\d|3[01])\./.test(h)) return false;
  return true;
}

async function substituteSecrets(s: string): Promise<string> {
  const { getSecret } = await import('./secrets.js');
  return s.replace(/\{\{\s*([A-Z0-9_]+)\s*\}\}/g, (_, key) => getSecret(key) || '');
}

/** Extract a value from an object by dotted path: "a.b.0.c" or "$.a.b". */
function getPath(obj: unknown, dotted?: string): unknown {
  if (!dotted) return obj;
  const parts = dotted.replace(/^\$\.?/, '').split('.').filter(Boolean);
  let cur: unknown = obj;
  for (const p of parts) {
    if (cur == null) return undefined;
    cur = (cur as Record<string, unknown>)[p];
  }
  return cur;
}

// ── Widget resolution ────────────────────────────────────────────────────

export interface WidgetData { ok: boolean; data?: unknown; error?: string; }

export async function resolveWidget(dashboardId: string, widget: Widget): Promise<WidgetData> {
  const src = widget.source;
  if (!src) return { ok: true, data: widget.config?.value ?? null };
  try {
    if (src.kind === 'static') return { ok: true, data: src.value };

    if (src.kind === 'local') {
      // Form widgets write under their own id; reader widgets (charts/metrics)
      // point at that id via config.readWidget. Default: this widget's own id.
      const readId = (widget.config?.readWidget as string) || widget.id;
      const rows = queryDashboardData(dashboardId, readId, src.sinceDays);
      const field = src.field;
      if (src.groupByDay) {
        // → [{ day, value }] aggregated per day
        const byDay = new Map<string, number[]>();
        for (const r of rows) {
          const day = new Date(r.created_at * 1000).toISOString().slice(0, 10);
          const v = Number((r.data as Record<string, unknown>)[field || 'value']);
          if (!byDay.has(day)) byDay.set(day, []);
          if (Number.isFinite(v)) byDay.get(day)!.push(v);
        }
        const out = Array.from(byDay.entries()).map(([day, vals]) => ({
          day, value: src.agg === 'avg' ? vals.reduce((a, b) => a + b, 0) / (vals.length || 1)
            : src.agg === 'count' ? vals.length
            : vals.reduce((a, b) => a + b, 0),
        }));
        return { ok: true, data: out };
      }
      const nums = rows.map((r) => Number((r.data as Record<string, unknown>)[field || 'value'])).filter(Number.isFinite);
      switch (src.agg) {
        case 'sum': return { ok: true, data: nums.reduce((a, b) => a + b, 0) };
        case 'avg': return { ok: true, data: nums.length ? nums.reduce((a, b) => a + b, 0) / nums.length : 0 };
        case 'count': return { ok: true, data: rows.length };
        case 'last': {
          const lastRow = rows.length ? rows[rows.length - 1].data : null;
          // If a specific field is named, return that scalar; else the whole entry.
          return { ok: true, data: (field && lastRow) ? (lastRow as Record<string, unknown>)[field] ?? null : lastRow };
        }
        default: return { ok: true, data: rows.map((r) => ({ ...r.data, _at: r.created_at, _id: r.id })) };
      }
    }

    if (src.kind === 'rss') {
      if (!src.url || !safeHttpUrl(src.url)) return { ok: false, error: 'Invalid/blocked feed URL' };
      const res = await fetch(src.url, { headers: { 'User-Agent': 'WildClaude/1.0' } });
      const xml = await res.text();
      const items: Array<{ title: string; link: string; date?: string }> = [];
      const re = /<(?:item|entry)\b[\s\S]*?<\/(?:item|entry)>/gi;
      let m: RegExpExecArray | null;
      while ((m = re.exec(xml)) && items.length < (src.limit || 12)) {
        const block = m[0];
        const title = (block.match(/<title[^>]*>([\s\S]*?)<\/title>/i)?.[1] || '').replace(/<!\[CDATA\[|\]\]>/g, '').trim();
        const link = (block.match(/<link[^>]*href="([^"]+)"/i)?.[1] || block.match(/<link[^>]*>([\s\S]*?)<\/link>/i)?.[1] || '').trim();
        const date = (block.match(/<(?:pubDate|updated|published)[^>]*>([\s\S]*?)<\/(?:pubDate|updated|published)>/i)?.[1] || '').trim();
        if (title) items.push({ title: title.slice(0, 200), link, date });
      }
      return { ok: true, data: items };
    }

    // http
    if (src.kind === 'http') {
      if (!src.url) return { ok: false, error: 'No URL' };
      const url = await substituteSecrets(src.url);
      if (!safeHttpUrl(url)) return { ok: false, error: 'Invalid/blocked URL (https + public host only)' };
      const headers: Record<string, string> = {};
      for (const [k, v] of Object.entries(src.headers || {})) headers[k] = await substituteSecrets(String(v));
      const res = await fetch(url, { method: src.method || 'GET', headers });
      if (!res.ok) return { ok: false, error: `HTTP ${res.status}` };
      const json = await res.json().catch(() => null);
      return { ok: true, data: getPath(json, src.jsonPath) };
    }

    return { ok: false, error: 'Unknown source kind' };
  } catch (err) {
    return { ok: false, error: err instanceof Error ? err.message.slice(0, 160) : 'resolve failed' };
  }
}

/** Append a tracker entry (form widget submit). */
export function recordEntry(dashboardId: string, widgetId: string, values: Record<string, unknown>): number {
  return insertDashboardData(dashboardId, widgetId, values);
}

// ── LLM generation ────────────────────────────────────────────────────────

const GEN_PROMPT = (request: string) => `You design dashboards for a personal AI assistant by emitting a JSON spec. Output ONLY the JSON object — no prose, no code fence.

User request: "${request}"

Schema:
{
  "title": "string",
  "icon": "one emoji",
  "description": "one line",
  "widgets": [
    {
      "id": "kebab-id",
      "type": "metric" | "chart" | "table" | "list" | "feed" | "form" | "note",
      "title": "string",
      "w": 1-12,                      // grid columns; metrics ~3, charts/tables ~8-12
      "source": {                     // omit for note/form
        "kind": "http" | "rss" | "local" | "static",
        // http: { "url": "https://...", "jsonPath": "a.b.0.c", "headers": {"Authorization":"Bearer {{SECRET_NAME}}"} }
        // rss:  { "url": "https://...", "limit": 12 }
        // local:{ "field": "weight", "agg": "last"|"sum"|"avg"|"count"|"list", "groupByDay": true, "sinceDays": 30 }
        // static:{ "value": ... }
      },
      "config": { ... }               // metric: {unit,format}; chart:{kind:"bar"|"line",x,y}; table:{columns:[...]}; form:{fields:[{name,label,type}]}; note:{markdown}
    }
  ]
}

Rules:
- Use PUBLIC, key-less https APIs where possible (e.g. CoinGecko, Frankfurter FX, public RSS). Only use {{SECRET_NAME}} placeholders when an API key is unavoidable, and name the secret clearly.
- For trackers (fitness, nutrition, habits, expenses), pair a "form" widget (writes via kind:local) with "chart"/"metric"/"table" widgets reading kind:local with the same field names.
- 3–8 widgets. Concrete, working sources — not placeholders. Sensible w values that tile a 12-col grid.
- Real, current API URLs you are confident exist. If unsure of an exact endpoint, prefer a note widget explaining what to wire up rather than a broken URL.`;

export async function generateDashboard(request: string, opts: { projectId?: string } = {}): Promise<{ ok: boolean; spec?: DashboardSpec; error?: string }> {
  try {
    const { runAgent } = await import('./agent.js');
    const { MODELS } = await import('./models.js');
    const result = await runAgent(GEN_PROMPT(request), undefined, () => {}, undefined, MODELS.opus);
    const raw = result.text || '';
    let parsed: Partial<DashboardSpec> | null = null;
    try { parsed = JSON.parse(raw); } catch {
      const fence = raw.match(/```(?:json)?\s*([\s\S]*?)```/);
      const start = raw.indexOf('{');
      const candidate = fence?.[1] || (start >= 0 ? raw.slice(start, raw.lastIndexOf('}') + 1) : '');
      try { parsed = JSON.parse(candidate); } catch { /* */ }
    }
    if (!parsed || !Array.isArray(parsed.widgets)) return { ok: false, error: 'Could not parse a dashboard spec from the model output.' };
    const spec = saveDashboard(normalizeSpec(parsed, { projectId: opts.projectId }));
    logger.info({ id: spec.id, widgets: spec.widgets.length }, 'dashboard generated');
    return { ok: true, spec };
  } catch (err) {
    return { ok: false, error: err instanceof Error ? err.message : 'generation failed' };
  }
}

// ── API routes ─────────────────────────────────────────────────────────
//
// Mounted under /api/dash (distinct from the legacy /api/dashboards used by
// external-dashboards.ts). The auth middleware in dashboard.ts covers these.

export function registerDashboardV2Routes(app: Hono): void {
  // List specs (optionally scoped to a project) + available templates.
  app.get('/api/dash', (c) => {
    const projectId = c.req.query('projectId') || undefined;
    return c.json({ dashboards: listDashboards(projectId), templates: listTemplates() });
  });

  app.get('/api/dash/templates', (c) => c.json({ templates: listTemplates() }));

  // Create: from a template ({templateId}), a prompt ({prompt}), or a raw spec.
  app.post('/api/dash', async (c) => {
    const body = await c.req.json().catch(() => ({})) as { templateId?: string; prompt?: string; spec?: Partial<DashboardSpec>; projectId?: string };
    if (body.templateId) {
      const spec = instantiateTemplate(body.templateId, { projectId: body.projectId });
      if (!spec) return c.json({ error: 'Unknown template' }, 404);
      return c.json({ dashboard: spec }, 201);
    }
    if (body.prompt) {
      const res = await generateDashboard(body.prompt, { projectId: body.projectId });
      if (!res.ok) return c.json({ error: res.error }, 422);
      return c.json({ dashboard: res.spec }, 201);
    }
    if (body.spec) {
      const spec = saveDashboard(normalizeSpec(body.spec, { projectId: body.projectId }));
      return c.json({ dashboard: spec }, 201);
    }
    return c.json({ error: 'Provide templateId, prompt, or spec' }, 400);
  });

  app.get('/api/dash/:id', (c) => {
    const spec = getDashboard(c.req.param('id'));
    return spec ? c.json({ dashboard: spec }) : c.json({ error: 'Not found' }, 404);
  });

  app.put('/api/dash/:id', async (c) => {
    const id = c.req.param('id');
    if (!getDashboard(id)) return c.json({ error: 'Not found' }, 404);
    const body = await c.req.json().catch(() => ({})) as Partial<DashboardSpec>;
    const spec = saveDashboard(normalizeSpec({ ...body, id }, { id }));
    return c.json({ dashboard: spec });
  });

  app.delete('/api/dash/:id', (c) => {
    return deleteDashboard(c.req.param('id')) ? c.json({ ok: true }) : c.json({ error: 'Not found' }, 404);
  });

  // Resolve one widget's data server-side.
  app.get('/api/dash/:id/widget/:wid', async (c) => {
    const spec = getDashboard(c.req.param('id'));
    if (!spec) return c.json({ error: 'Not found' }, 404);
    const widget = spec.widgets.find((w) => w.id === c.req.param('wid'));
    if (!widget) return c.json({ error: 'No such widget' }, 404);
    return c.json(await resolveWidget(spec.id, widget));
  });

  // Append a tracker entry (form submit).
  app.post('/api/dash/:id/data', async (c) => {
    const spec = getDashboard(c.req.param('id'));
    if (!spec) return c.json({ error: 'Not found' }, 404);
    const body = await c.req.json().catch(() => ({})) as { widgetId?: string; values?: Record<string, unknown> };
    if (!body.widgetId || !body.values) return c.json({ error: 'widgetId and values required' }, 400);
    const rowId = recordEntry(spec.id, body.widgetId, body.values);
    return c.json({ ok: true, id: rowId }, 201);
  });

  // Generate a spec from a chat prompt without persisting attachment to a project.
  app.post('/api/dash/generate', async (c) => {
    const body = await c.req.json().catch(() => ({})) as { prompt?: string; projectId?: string };
    if (!body.prompt) return c.json({ error: 'prompt required' }, 400);
    const res = await generateDashboard(body.prompt, { projectId: body.projectId });
    return res.ok ? c.json({ dashboard: res.spec }, 201) : c.json({ error: res.error }, 422);
  });
}
