/**
 * Declarative dashboard engine.
 *
 * A dashboard is a JSON SPEC of widgets; the frontend renders any spec
 * generically and this module resolves each widget's data server-side (so
 * secrets and CORS are handled here, never in the browser). Specs can be:
 *   - hand-built / template-instantiated
 *   - generated by the LLM from a plain-language request ("make me a crypto dashboard")
 *   - scoped to a project container
 *
 * Widget data sources:
 *   - http   : fetch a JSON API, extract via a dotted path; {{SECRET}} placeholders
 *              in url/headers are filled from the encrypted secret store
 *   - rss     : fetch + parse an RSS/Atom feed
 *   - local   : query the dashboard_data table (tracker widgets; forms write here)
 *   - static  : a literal value
 *
 * Specs live in USER_DATA_DIR/dashboards/<id>.json (versioned in the user-data repo).
 */

import fs from 'fs';
import path from 'path';
import dns from 'dns';
import type { Hono } from 'hono';

import { USER_DATA_DIR } from './paths.js';
import { logger } from './logger.js';
import { insertDashboardData, queryDashboardData } from './db.js';
import { DEFAULT_DASHBOARD_TEMPLATES } from './dashboard-templates.js';
import { commitUserData } from './user-data-git.js';

/** fetch() with a hard timeout so a slow/hanging API can't stall widget resolution. */
async function fetchWithTimeout(url: string, opts: RequestInit = {}, ms = 8000): Promise<Response> {
  const ctrl = new AbortController();
  const timer = setTimeout(() => ctrl.abort(), ms);
  try { return await fetch(url, { ...opts, signal: ctrl.signal }); }
  finally { clearTimeout(timer); }
}

// ── Types ──────────────────────────────────────────────────────────────

export type WidgetType = 'metric' | 'chart' | 'table' | 'list' | 'feed' | 'form' | 'note' | 'gauge' | 'insight';

export interface WidgetSource {
  kind: 'http' | 'rss' | 'local' | 'static';
  // http
  url?: string;
  headers?: Record<string, string>;
  method?: string;
  jsonPath?: string;          // dotted path into the JSON response (e.g. "data.0.current_price")
  // rss
  limit?: number;
  // local
  field?: string;             // which field of each entry to aggregate/plot
  agg?: 'sum' | 'avg' | 'count' | 'last' | 'list' | 'streak' | 'delta';
  sinceDays?: number;
  groupByDay?: boolean;
  // static
  value?: unknown;
}

const WIDGET_TYPES: WidgetType[] = ['metric', 'chart', 'table', 'list', 'feed', 'form', 'note', 'gauge', 'insight'];

export interface Widget {
  id: string;
  type: WidgetType;
  title: string;
  w?: number;                 // grid columns 1–12 (default 4)
  source?: WidgetSource;
  config?: Record<string, unknown>; // type-specific (unit, columns, fields[], etc.)
  refreshSec?: number;
}

export interface DashboardSpec {
  id: string;
  title: string;
  icon?: string;
  description?: string;
  widgets: Widget[];
  projectId?: string;
  builtinTemplate?: string;
  createdAt: number;
  updatedAt: number;
}

const DASH_DIR = path.join(USER_DATA_DIR, 'dashboards');

// ── Store ──────────────────────────────────────────────────────────────

function specPath(id: string): string {
  // Guard against traversal — ids are slugs.
  const clean = String(id).replace(/[^a-z0-9_-]/gi, '');
  return path.join(DASH_DIR, `${clean}.json`);
}

export function listDashboards(projectId?: string): DashboardSpec[] {
  try {
    if (!fs.existsSync(DASH_DIR)) return [];
    const specs: DashboardSpec[] = [];
    for (const f of fs.readdirSync(DASH_DIR)) {
      if (!f.endsWith('.json')) continue;
      try {
        const s = JSON.parse(fs.readFileSync(path.join(DASH_DIR, f), 'utf8')) as DashboardSpec;
        if (projectId === undefined || s.projectId === projectId) specs.push(s);
      } catch { /* skip corrupt */ }
    }
    return specs.sort((a, b) => (b.updatedAt || 0) - (a.updatedAt || 0));
  } catch { return []; }
}

export function getDashboard(id: string): DashboardSpec | null {
  try { return JSON.parse(fs.readFileSync(specPath(id), 'utf8')) as DashboardSpec; } catch { return null; }
}

const slugify = (s: string) => (s || 'dashboard').toLowerCase().trim().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '').slice(0, 40) || 'dashboard';

/** Validate + normalize a raw spec object (from LLM/import/template). */
export function normalizeSpec(raw: Partial<DashboardSpec>, opts: { id?: string; projectId?: string } = {}): DashboardSpec {
  const now = Date.now();
  const id = opts.id || slugify(raw.id || raw.title || 'dashboard') + '-' + now.toString(36).slice(-4);
  const widgets: Widget[] = (Array.isArray(raw.widgets) ? raw.widgets : []).slice(0, 30).map((w, i) => ({
    id: (w as Widget).id || `w${i}`,
    type: (WIDGET_TYPES.includes((w as Widget).type) ? (w as Widget).type : 'note') as WidgetType,
    title: String((w as Widget).title || 'Widget').slice(0, 120),
    w: Math.min(12, Math.max(1, (w as Widget).w || 4)),
    source: (w as Widget).source,
    config: (w as Widget).config || {},
    refreshSec: (w as Widget).refreshSec,
  }));
  return {
    id,
    title: String(raw.title || 'Dashboard').slice(0, 120),
    icon: String(raw.icon || '📊').slice(0, 8),
    description: raw.description ? String(raw.description).slice(0, 400) : undefined,
    widgets,
    projectId: opts.projectId ?? raw.projectId,
    builtinTemplate: raw.builtinTemplate,
    createdAt: raw.createdAt || now,
    updatedAt: now,
  };
}

export function saveDashboard(spec: DashboardSpec): DashboardSpec {
  fs.mkdirSync(DASH_DIR, { recursive: true });
  const normalized = { ...spec, updatedAt: Date.now() };
  fs.writeFileSync(specPath(spec.id), JSON.stringify(normalized, null, 2));
  commitUserData(`dashboard: save ${spec.id}`);
  return normalized;
}

export function deleteDashboard(id: string): boolean {
  try { fs.unlinkSync(specPath(id)); commitUserData(`dashboard: delete ${id}`); return true; } catch { return false; }
}

// ── Templates ──────────────────────────────────────────────────────────

export function listTemplates(): Array<{ id: string; title: string; icon: string; description: string }> {
  return DEFAULT_DASHBOARD_TEMPLATES.map((t) => ({ id: t.id, title: t.title, icon: t.icon || '📊', description: t.description || '' }));
}

export function instantiateTemplate(templateId: string, opts: { projectId?: string } = {}): DashboardSpec | null {
  const tpl = DEFAULT_DASHBOARD_TEMPLATES.find((t) => t.id === templateId);
  if (!tpl) return null;
  const spec = normalizeSpec({ ...tpl, builtinTemplate: templateId }, { projectId: opts.projectId });
  return saveDashboard(spec);
}

// ── SSRF guard + secret substitution ─────────────────────────────────────

function isPrivateIp(ip: string): boolean {
  // IPv4 private/loopback/link-local/CGNAT + IPv6 loopback/ULA/link-local.
  if (/^(127\.|10\.|192\.168\.|169\.254\.|0\.|100\.(6[4-9]|[7-9]\d|1[01]\d|12[0-7])\.)/.test(ip)) return true;
  if (/^172\.(1[6-9]|2\d|3[01])\./.test(ip)) return true;
  if (ip === '::1' || ip === '::' || /^f[cd][0-9a-f]{2}:/i.test(ip) || /^fe80:/i.test(ip)) return true;
  return false;
}

/** Sync URL sanity: https + not an obviously-internal hostname/literal IP. */
function safeHttpUrl(url: string): boolean {
  let u: URL;
  try { u = new URL(url); } catch { return false; }
  if (u.protocol !== 'https:') return false;
  const h = u.hostname.toLowerCase();
  if (h === 'localhost' || h === '::1' || h.endsWith('.local') || h.endsWith('.internal') || !h.includes('.')) return false;
  if (isPrivateIp(h)) return false;
  return true;
}

/**
 * Full SSRF check: sync sanity + DNS resolution so a public hostname that
 * resolves to a private/loopback address (DNS-rebinding) is also blocked.
 */
async function isSafeHttpTarget(url: string): Promise<boolean> {
  if (!safeHttpUrl(url)) return false;
  try {
    const host = new URL(url).hostname;
    const addrs = await dns.promises.lookup(host, { all: true });
    if (!addrs.length) return false;
    return addrs.every((a) => !isPrivateIp(a.address));
  } catch {
    return false; // resolution failed → don't fetch
  }
}

async function substituteSecrets(s: string): Promise<string> {
  const { getSecret } = await import('./secrets.js');
  return s.replace(/\{\{\s*([A-Z0-9_]+)\s*\}\}/g, (_, key) => getSecret(key) || '');
}

/** Extract a value from an object by dotted path: "a.b.0.c" or "$.a.b". */
function getPath(obj: unknown, dotted?: string): unknown {
  if (!dotted) return obj;
  const parts = dotted.replace(/^\$\.?/, '').split('.').filter(Boolean);
  let cur: unknown = obj;
  for (const p of parts) {
    if (cur == null) return undefined;
    cur = (cur as Record<string, unknown>)[p];
  }
  return cur;
}

// ── Widget resolution ────────────────────────────────────────────────────

export interface WidgetData { ok: boolean; data?: unknown; error?: string; }

export async function resolveWidget(dashboardId: string, widget: Widget): Promise<WidgetData> {
  const src = widget.source;
  if (!src) return { ok: true, data: widget.config?.value ?? null };
  try {
    if (src.kind === 'static') return { ok: true, data: src.value };

    if (src.kind === 'local') {
      // Form widgets write under their own id; reader widgets (charts/metrics)
      // point at that id via config.readWidget. Default: this widget's own id.
      const readId = (widget.config?.readWidget as string) || widget.id;
      const rows = queryDashboardData(dashboardId, readId, src.sinceDays);
      const field = src.field;
      if (src.groupByDay) {
        // → [{ day, value }] aggregated per day
        const byDay = new Map<string, number[]>();
        for (const r of rows) {
          const day = new Date(r.created_at * 1000).toISOString().slice(0, 10);
          const v = Number((r.data as Record<string, unknown>)[field || 'value']);
          if (!byDay.has(day)) byDay.set(day, []);
          if (Number.isFinite(v)) byDay.get(day)!.push(v);
        }
        const out = Array.from(byDay.entries()).map(([day, vals]) => ({
          day, value: src.agg === 'avg' ? vals.reduce((a, b) => a + b, 0) / (vals.length || 1)
            : src.agg === 'count' ? vals.length
            : vals.reduce((a, b) => a + b, 0),
        }));
        return { ok: true, data: out };
      }
      const nums = rows.map((r) => Number((r.data as Record<string, unknown>)[field || 'value'])).filter(Number.isFinite);
      switch (src.agg) {
        case 'sum': return { ok: true, data: nums.reduce((a, b) => a + b, 0) };
        case 'avg': return { ok: true, data: nums.length ? nums.reduce((a, b) => a + b, 0) / nums.length : 0 };
        case 'count': return { ok: true, data: rows.length };
        case 'last': {
          const lastRow = rows.length ? rows[rows.length - 1].data : null;
          // If a specific field is named, return that scalar; else the whole entry.
          return { ok: true, data: (field && lastRow) ? (lastRow as Record<string, unknown>)[field] ?? null : lastRow };
        }
        case 'streak': {
          // Consecutive days (ending today or yesterday) with at least one entry.
          const days = new Set(rows.map((r) => new Date(r.created_at * 1000).toISOString().slice(0, 10)));
          let streak = 0;
          const cursor = new Date();
          // Allow the streak to count from today or yesterday so a not-yet-logged today doesn't reset it.
          if (!days.has(cursor.toISOString().slice(0, 10))) cursor.setUTCDate(cursor.getUTCDate() - 1);
          while (days.has(cursor.toISOString().slice(0, 10))) { streak++; cursor.setUTCDate(cursor.getUTCDate() - 1); }
          return { ok: true, data: streak };
        }
        case 'delta': {
          // Current period vs the preceding equal-length period (sum of field).
          const win = src.sinceDays || 7;
          const cutoff = Math.floor(Date.now() / 1000) - win * 86400;
          const allRows = queryDashboardData(dashboardId, readId); // unbounded, then split
          const sumIn = (rs: typeof allRows) => rs.reduce((a, r) => a + (Number((r.data as Record<string, unknown>)[field || 'value']) || 0), 0);
          const current = sumIn(allRows.filter((r) => r.created_at >= cutoff));
          const prev = sumIn(allRows.filter((r) => r.created_at >= cutoff - win * 86400 && r.created_at < cutoff));
          const changePct = prev === 0 ? null : ((current - prev) / Math.abs(prev)) * 100;
          return { ok: true, data: { current, previous: prev, changePct } };
        }
        default: return { ok: true, data: rows.map((r) => ({ ...r.data, _at: r.created_at, _id: r.id })) };
      }
    }

    if (src.kind === 'rss') {
      if (!src.url || !(await isSafeHttpTarget(src.url))) return { ok: false, error: 'Invalid/blocked feed URL' };
      const res = await fetchWithTimeout(src.url, { headers: { 'User-Agent': 'WildClaude/1.0' } });
      const xml = await res.text();
      const items: Array<{ title: string; link: string; date?: string }> = [];
      const re = /<(?:item|entry)\b[\s\S]*?<\/(?:item|entry)>/gi;
      let m: RegExpExecArray | null;
      while ((m = re.exec(xml)) && items.length < (src.limit || 12)) {
        const block = m[0];
        const title = (block.match(/<title[^>]*>([\s\S]*?)<\/title>/i)?.[1] || '').replace(/<!\[CDATA\[|\]\]>/g, '').trim();
        const link = (block.match(/<link[^>]*href="([^"]+)"/i)?.[1] || block.match(/<link[^>]*>([\s\S]*?)<\/link>/i)?.[1] || '').trim();
        const date = (block.match(/<(?:pubDate|updated|published)[^>]*>([\s\S]*?)<\/(?:pubDate|updated|published)>/i)?.[1] || '').trim();
        if (title) items.push({ title: title.slice(0, 200), link, date });
      }
      return { ok: true, data: items };
    }

    // http
    if (src.kind === 'http') {
      if (!src.url) return { ok: false, error: 'No URL' };
      const url = await substituteSecrets(src.url);
      if (!(await isSafeHttpTarget(url))) return { ok: false, error: 'Invalid/blocked URL (https + public host only)' };
      const headers: Record<string, string> = {};
      for (const [k, v] of Object.entries(src.headers || {})) headers[k] = await substituteSecrets(String(v));
      const res = await fetchWithTimeout(url, { method: src.method || 'GET', headers });
      if (!res.ok) return { ok: false, error: `HTTP ${res.status}` };
      const json = await res.json().catch(() => null);
      return { ok: true, data: getPath(json, src.jsonPath) };
    }

    return { ok: false, error: 'Unknown source kind' };
  } catch (err) {
    return { ok: false, error: err instanceof Error ? err.message.slice(0, 160) : 'resolve failed' };
  }
}

/** Append a tracker entry (form widget submit). */
export function recordEntry(dashboardId: string, widgetId: string, values: Record<string, unknown>): number {
  return insertDashboardData(dashboardId, widgetId, values);
}

// ── LLM helpers ────────────────────────────────────────────────────────────

/** Robustly pull a JSON object/array out of model output (handles fences/prose). */
function extractJson<T = unknown>(raw: string): T | null {
  if (!raw) return null;
  try { return JSON.parse(raw) as T; } catch { /* */ }
  const fence = raw.match(/```(?:json)?\s*([\s\S]*?)```/);
  if (fence) { try { return JSON.parse(fence[1]) as T; } catch { /* */ } }
  // Balance from the first opening brace/bracket.
  const start = raw.search(/[{[]/);
  if (start >= 0) {
    const open = raw[start];
    const close = open === '{' ? '}' : ']';
    const end = raw.lastIndexOf(close);
    if (end > start) { try { return JSON.parse(raw.slice(start, end + 1)) as T; } catch { /* */ } }
  }
  return null;
}

async function ask(prompt: string, model: string): Promise<string> {
  const { runAgent } = await import('./agent.js');
  const result = await runAgent(prompt, undefined, () => {}, undefined, model);
  return result.text || '';
}

// ── Clarifying-questions planner ──────────────────────────────────────────
//
// Before generating, we ask the model to (a) understand the request, (b) propose
// the widgets it would build, and (c) surface a few high-leverage questions so
// the user shapes the result. The frontend renders these; answers feed generation.

export interface DashboardPlan {
  title: string;
  icon: string;
  summary: string;
  recommendedWidgets: string[];
  questions: Array<{ id: string; question: string; type: 'choice' | 'multi' | 'text'; options?: string[]; default?: string }>;
}

const PLAN_PROMPT = (request: string) => `A user wants a personal dashboard: "${request}".

Think about what would make this dashboard genuinely useful and delightful, then output ONLY a JSON object (no prose, no fence):
{
  "title": "concise dashboard name",
  "icon": "one relevant emoji",
  "summary": "one sentence describing what you'd build",
  "recommendedWidgets": ["short phrase per widget you'd include — favour charts, trends, gauges, streaks and at-a-glance metrics over plain tables"],
  "questions": [
    // 2-4 high-leverage questions that meaningfully change the design. Prefer "choice"/"multi" with concrete options.
    { "id": "kebab", "question": "…?", "type": "choice", "options": ["A","B"], "default": "A" }
  ]
}

Guidance for questions: ask about units/currency, time range, whether to track a goal/target, which metrics matter most, data they'd log manually vs. pull from APIs, refresh cadence. Keep them concrete and answerable in one tap.`;

export async function planDashboard(request: string): Promise<{ ok: boolean; plan?: DashboardPlan; error?: string }> {
  try {
    const { MODELS } = await import('./models.js');
    const raw = await ask(PLAN_PROMPT(request), MODELS.sonnet);
    const plan = extractJson<DashboardPlan>(raw);
    if (!plan || !Array.isArray(plan.questions)) return { ok: false, error: 'Could not produce a plan.' };
    // Bound it.
    plan.questions = plan.questions.slice(0, 4).map((q, i) => ({
      id: q.id || `q${i}`, question: String(q.question || '').slice(0, 200),
      type: (['choice', 'multi', 'text'].includes(q.type) ? q.type : 'text'),
      options: Array.isArray(q.options) ? q.options.slice(0, 6).map((o) => String(o).slice(0, 60)) : undefined,
      default: q.default ? String(q.default).slice(0, 60) : undefined,
    }));
    plan.recommendedWidgets = (Array.isArray(plan.recommendedWidgets) ? plan.recommendedWidgets : []).slice(0, 10).map((w) => String(w).slice(0, 120));
    return { ok: true, plan };
  } catch (err) {
    return { ok: false, error: err instanceof Error ? err.message : 'plan failed' };
  }
}

// ── Spec generation ────────────────────────────────────────────────────────

const GEN_PROMPT = (request: string, answers?: Record<string, string>) => `You design rich, visual dashboards for a personal AI assistant by emitting a JSON spec. Output ONLY the JSON object — no prose, no code fence.

User request: "${request}"
${answers && Object.keys(answers).length ? `\nThe user answered these design questions — honour them:\n${Object.entries(answers).map(([k, v]) => `- ${k}: ${v}`).join('\n')}` : ''}

Schema:
{
  "title": "string",
  "icon": "one emoji",
  "description": "one line",
  "widgets": [
    {
      "id": "kebab-id",
      "type": "metric" | "chart" | "table" | "list" | "feed" | "form" | "note" | "gauge" | "insight",
      "title": "string",
      "w": 1-12,                      // grid columns; metrics/gauges ~3-4, charts/tables ~8-12
      "source": {                     // omit for note; form has source {"kind":"local"}
        "kind": "http" | "rss" | "local" | "static",
        // http:  { "url": "https://...", "jsonPath": "a.b.0.c", "headers": {"Authorization":"Bearer {{SECRET_NAME}}"} }
        // rss:   { "url": "https://...", "limit": 12 }
        // local: { "field":"weight", "agg":"last|sum|avg|count|list|streak|delta", "groupByDay":true, "sinceDays":30, "readWidget":"<form-widget-id>" }
        // static:{ "value": ... }
      },
      "config": { ... }
      // metric: {unit, format:"currency"|"percent"|"compact"|"number", decimals, readWidget}
      // gauge:  {target:<number>, unit, readWidget}   ← progress toward a goal (use with agg sum/last/count)
      // chart:  {kind:"bar"|"line", x:"day", y:"value", readWidget}
      // table:  {columns:[{key,label,format}], readWidget}
      // form:   {fields:[{name,label,type:"number"|"text"}], submitLabel}
      // insight:{readWidget, field}   ← an on-demand AI summary of the logged data (no source needed)
      // note:   {markdown}
    }
  ]
}

Design rules — make it feel premium, not a spreadsheet:
- LEAD WITH VISUALS: prefer charts (line for trends, bar for comparisons), gauges for goals, and big metrics with deltas over plain tables. Every tracker dashboard should have at least one chart and one gauge or delta metric.
- For manual trackers (fitness, nutrition, habits, mood, expenses, reading): include ONE "form" widget (kind:local) whose field names are reused by reader widgets via "readWidget":"<that form's id>". Add a "metric" with agg:"delta" (shows ▲/▼ vs previous period), a "chart" with groupByDay over 30 days, and where a goal makes sense a "gauge" with a target. For daily-habit trackers add a "streak" metric (agg:"streak"). Add ONE "insight" widget so the user gets an AI read on their data.
- Use PUBLIC key-less https APIs where possible (CoinGecko, Frankfurter FX, open RSS). Only use {{SECRET_NAME}} when a key is unavoidable; name it clearly.
- 4–8 widgets. Concrete, working sources — never placeholders. Sensible w values that tile a 12-col grid (rows should add up to ~12).
- Real, current API URLs you're confident exist; if unsure, use a "note" widget explaining what to wire up rather than a broken URL.`;

export async function generateDashboard(request: string, opts: { projectId?: string; answers?: Record<string, string> } = {}): Promise<{ ok: boolean; spec?: DashboardSpec; error?: string }> {
  try {
    const { MODELS } = await import('./models.js');
    const raw = await ask(GEN_PROMPT(request, opts.answers), MODELS.opus);
    const parsed = extractJson<Partial<DashboardSpec>>(raw);
    if (!parsed || !Array.isArray(parsed.widgets)) return { ok: false, error: 'Could not parse a dashboard spec from the model output.' };
    const spec = saveDashboard(normalizeSpec(parsed, { projectId: opts.projectId }));
    logger.info({ id: spec.id, widgets: spec.widgets.length }, 'dashboard generated');
    return { ok: true, spec };
  } catch (err) {
    return { ok: false, error: err instanceof Error ? err.message : 'generation failed' };
  }
}

// ── Conversational refinement ──────────────────────────────────────────────
//
// Take an existing spec + a plain-language (or voice-transcribed) instruction
// and return an updated spec. Widget ids are PRESERVED for any kept widget so
// logged tracker data (keyed by widget id) and readWidget links stay intact.

const REFINE_PROMPT = (spec: DashboardSpec, instruction: string) => `You are editing an existing personal dashboard. Apply the user's instruction and output ONLY the complete, updated dashboard JSON (same schema) — no prose, no code fence.

Current dashboard JSON:
${JSON.stringify({ title: spec.title, icon: spec.icon, description: spec.description, widgets: spec.widgets }, null, 2)}

User instruction: "${instruction}"

Rules:
- Return the FULL updated spec (all widgets you want to keep, not just changes).
- PRESERVE the "id" of every widget you keep unchanged or merely tweak — only assign new ids to genuinely new widgets. Tracker data and "readWidget" links are keyed by widget id, so renaming an existing widget loses its data.
- Keep working data sources intact unless asked to change them. Honour the same widget schema (types: metric, chart, table, list, feed, form, note, gauge, insight; local aggs: last/sum/avg/count/list/streak/delta).
- Respect requests about size ("bigger" → larger w up to 12), order, adding/removing widgets, changing chart kinds, targets, units, time ranges, titles.
- Keep w values sensible so rows tile a 12-col grid.`;

export async function refineDashboard(id: string, instruction: string): Promise<{ ok: boolean; spec?: DashboardSpec; error?: string }> {
  const current = getDashboard(id);
  if (!current) return { ok: false, error: 'No such dashboard' };
  try {
    const { MODELS } = await import('./models.js');
    const raw = await ask(REFINE_PROMPT(current, instruction), MODELS.opus);
    const parsed = extractJson<Partial<DashboardSpec>>(raw);
    if (!parsed || !Array.isArray(parsed.widgets)) return { ok: false, error: 'Could not parse the updated dashboard.' };
    // Preserve identity: keep the same id, projectId, template marker, createdAt.
    const merged = normalizeSpec(
      { ...parsed, id: current.id, projectId: current.projectId, builtinTemplate: current.builtinTemplate, createdAt: current.createdAt },
      { id: current.id, projectId: current.projectId },
    );
    const spec = saveDashboard(merged);
    logger.info({ id: spec.id, widgets: spec.widgets.length }, 'dashboard refined');
    return { ok: true, spec };
  } catch (err) {
    return { ok: false, error: err instanceof Error ? err.message : 'refine failed' };
  }
}

// ── Voice / natural-language entry parsing ─────────────────────────────────
//
// A tracker form widget can be filled by speaking. The browser transcribes via
// the Web Speech API; we map that free text onto the widget's fields with Haiku.

export async function parseEntry(dashboardId: string, widgetId: string, transcript: string): Promise<{ ok: boolean; values?: Record<string, unknown>; error?: string }> {
  const spec = getDashboard(dashboardId);
  if (!spec) return { ok: false, error: 'No such dashboard' };
  const widget = spec.widgets.find((w) => w.id === widgetId);
  const fields = (widget?.config?.fields as Array<{ name: string; label?: string; type?: string }>) || [];
  if (!fields.length) return { ok: false, error: 'Widget has no fields to fill' };
  try {
    const { MODELS } = await import('./models.js');
    const prompt = `Extract structured values from a spoken log entry. Output ONLY a JSON object mapping field names to values.

Fields (name : type : label):
${fields.map((f) => `- ${f.name} : ${f.type || 'text'} : ${f.label || f.name}`).join('\n')}

Spoken entry: "${transcript.slice(0, 400)}"

Rules: numbers as numbers (strip units like "kg","cal","minutes"); omit fields not mentioned; never invent values. Example output: {"weight":80,"sleep":7.5}`;
    const raw = await ask(prompt, MODELS.haiku);
    const obj = extractJson<Record<string, unknown>>(raw) || {};
    // Coerce by declared type and drop unknown keys.
    const values: Record<string, unknown> = {};
    for (const f of fields) {
      if (!(f.name in obj)) continue;
      values[f.name] = f.type === 'number' ? Number(obj[f.name]) : obj[f.name];
    }
    return { ok: true, values };
  } catch (err) {
    return { ok: false, error: err instanceof Error ? err.message : 'parse failed' };
  }
}

// ── On-demand AI insight over a widget's logged data ───────────────────────

export async function generateInsight(dashboardId: string, widgetId: string): Promise<{ ok: boolean; text?: string; error?: string }> {
  const spec = getDashboard(dashboardId);
  if (!spec) return { ok: false, error: 'No such dashboard' };
  const widget = spec.widgets.find((w) => w.id === widgetId);
  if (!widget) return { ok: false, error: 'No such widget' };
  const readId = (widget.config?.readWidget as string) || widget.id;
  const rows = queryDashboardData(dashboardId, readId, 60);
  if (!rows.length) return { ok: true, text: 'No data logged yet — start logging and I’ll surface trends here.' };
  try {
    const { MODELS } = await import('./models.js');
    const sample = rows.slice(-40).map((r) => ({ at: new Date(r.created_at * 1000).toISOString().slice(0, 10), ...r.data }));
    const prompt = `You are a concise personal-analytics coach. Given these logged entries for "${spec.title} → ${widget.title}", write 2-3 short sentences of genuinely useful insight: trends, averages, streaks, anomalies, and one actionable nudge. No preamble, no markdown headers.

Data (JSON): ${JSON.stringify(sample)}`;
    const text = (await ask(prompt, MODELS.haiku)).trim();
    return { ok: true, text: text.slice(0, 800) };
  } catch (err) {
    return { ok: false, error: err instanceof Error ? err.message : 'insight failed' };
  }
}

// ── API routes ─────────────────────────────────────────────────────────
//
// Mounted under /api/dash (distinct from the legacy /api/dashboards used by
// external-dashboards.ts). The auth middleware in dashboard.ts covers these.

export function registerDashboardV2Routes(app: Hono): void {
  // List specs (optionally scoped to a project) + available templates.
  app.get('/api/dash', (c) => {
    const projectId = c.req.query('projectId') || undefined;
    return c.json({ dashboards: listDashboards(projectId), templates: listTemplates() });
  });

  app.get('/api/dash/templates', (c) => c.json({ templates: listTemplates() }));

  // Step 1 of the guided flow: analyse the request → recommended widgets + clarifying questions.
  app.post('/api/dash/plan', async (c) => {
    const body = await c.req.json().catch(() => ({})) as { prompt?: string };
    if (!body.prompt) return c.json({ error: 'prompt required' }, 400);
    const res = await planDashboard(body.prompt);
    return res.ok ? c.json({ plan: res.plan }) : c.json({ error: res.error }, 422);
  });

  // Create: from a template ({templateId}), a prompt (+ optional answers), or a raw spec.
  app.post('/api/dash', async (c) => {
    const body = await c.req.json().catch(() => ({})) as { templateId?: string; prompt?: string; answers?: Record<string, string>; spec?: Partial<DashboardSpec>; projectId?: string };
    if (body.templateId) {
      const spec = instantiateTemplate(body.templateId, { projectId: body.projectId });
      if (!spec) return c.json({ error: 'Unknown template' }, 404);
      return c.json({ dashboard: spec }, 201);
    }
    if (body.prompt) {
      const res = await generateDashboard(body.prompt, { projectId: body.projectId, answers: body.answers });
      if (!res.ok) return c.json({ error: res.error }, 422);
      return c.json({ dashboard: res.spec }, 201);
    }
    if (body.spec) {
      const spec = saveDashboard(normalizeSpec(body.spec, { projectId: body.projectId }));
      return c.json({ dashboard: spec }, 201);
    }
    return c.json({ error: 'Provide templateId, prompt, or spec' }, 400);
  });

  app.get('/api/dash/:id', (c) => {
    const spec = getDashboard(c.req.param('id'));
    return spec ? c.json({ dashboard: spec }) : c.json({ error: 'Not found' }, 404);
  });

  app.put('/api/dash/:id', async (c) => {
    const id = c.req.param('id');
    if (!getDashboard(id)) return c.json({ error: 'Not found' }, 404);
    const body = await c.req.json().catch(() => ({})) as Partial<DashboardSpec>;
    const spec = saveDashboard(normalizeSpec({ ...body, id }, { id }));
    return c.json({ dashboard: spec });
  });

  app.delete('/api/dash/:id', (c) => {
    return deleteDashboard(c.req.param('id')) ? c.json({ ok: true }) : c.json({ error: 'Not found' }, 404);
  });

  // Resolve one widget's data server-side.
  app.get('/api/dash/:id/widget/:wid', async (c) => {
    const spec = getDashboard(c.req.param('id'));
    if (!spec) return c.json({ error: 'Not found' }, 404);
    const widget = spec.widgets.find((w) => w.id === c.req.param('wid'));
    if (!widget) return c.json({ error: 'No such widget' }, 404);
    return c.json(await resolveWidget(spec.id, widget));
  });

  // Append a tracker entry (form submit).
  app.post('/api/dash/:id/data', async (c) => {
    const spec = getDashboard(c.req.param('id'));
    if (!spec) return c.json({ error: 'Not found' }, 404);
    const body = await c.req.json().catch(() => ({})) as { widgetId?: string; values?: Record<string, unknown> };
    if (!body.widgetId || !body.values) return c.json({ error: 'widgetId and values required' }, 400);
    const rowId = recordEntry(spec.id, body.widgetId, body.values);
    return c.json({ ok: true, id: rowId }, 201);
  });

  // Conversational/voice refinement: update the spec from a plain-language instruction.
  app.post('/api/dash/:id/refine', async (c) => {
    const body = await c.req.json().catch(() => ({})) as { prompt?: string };
    if (!body.prompt) return c.json({ error: 'prompt required' }, 400);
    const res = await refineDashboard(c.req.param('id'), body.prompt);
    return res.ok ? c.json({ dashboard: res.spec }) : c.json({ error: res.error }, 422);
  });

  // Voice/NL → structured field values for a form widget (browser transcribes, we map).
  app.post('/api/dash/:id/parse-entry', async (c) => {
    const body = await c.req.json().catch(() => ({})) as { widgetId?: string; transcript?: string };
    if (!body.widgetId || !body.transcript) return c.json({ error: 'widgetId and transcript required' }, 400);
    const res = await parseEntry(c.req.param('id'), body.widgetId, body.transcript);
    return res.ok ? c.json({ values: res.values }) : c.json({ error: res.error }, 422);
  });

  // On-demand AI insight over a widget's logged data.
  app.post('/api/dash/:id/insight/:wid', async (c) => {
    const res = await generateInsight(c.req.param('id'), c.req.param('wid'));
    return res.ok ? c.json({ text: res.text }) : c.json({ error: res.error }, 422);
  });

  // Generate a spec from a chat prompt without persisting attachment to a project.
  app.post('/api/dash/generate', async (c) => {
    const body = await c.req.json().catch(() => ({})) as { prompt?: string; projectId?: string };
    if (!body.prompt) return c.json({ error: 'prompt required' }, 400);
    const res = await generateDashboard(body.prompt, { projectId: body.projectId });
    return res.ok ? c.json({ dashboard: res.spec }, 201) : c.json({ error: res.error }, 422);
  });
}
